**NumPy_Basics_2**

**Practices**

**Practice**

In [3]:
import numpy as np
new_array = np.zeros((8,8))
for i in list(range(0,8,2)):
  new_array[:,i] = 1
print(new_array)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


**Practice** Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:                                                   
[[0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]]

**Practices**

In [4]:
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [30]:
array_x = np.ones((10,10))
array_x[0] = 0
array_x[9] = 0
array_x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
my_array = np.arange(0,63,3)
new_array = my_array[::2]
new_array

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54, 60])

In [16]:
array_1 = np.array([10,20,30,40,50])
array_2 = np.array([5,10,20,34,48])
final_array = np.setxor1d(array_1,array_2)
final_array

array([ 5, 30, 34, 40, 48, 50])

In [39]:
my_array = np.arange(0,160,3)
print("size: ", my_array.size)
print(my_array.itemsize)
print(my_array.nbytes)

size:  54
8
432


In [93]:
new_array = np.arange(0,150,5).reshape(5,6)
new_array = np.sort(new_array)[::-1]
new_array = np.sort(new_array)
new_array

array([[120, 125, 130, 135, 140, 145],
       [ 90,  95, 100, 105, 110, 115],
       [ 60,  65,  70,  75,  80,  85],
       [ 30,  35,  40,  45,  50,  55],
       [  0,   5,  10,  15,  20,  25]])

In [96]:
new_array = np.delete(new_array,2,1)
new_array

array([[120, 125, 135, 140, 145],
       [ 90,  95, 105, 110, 115],
       [ 30,  35,  45,  50,  55],
       [  0,   5,  15,  20,  25]])

In [99]:
np.shape(new_array)
new_array.reshape(10,2)

array([[120, 125],
       [135, 140],
       [145,  90],
       [ 95, 105],
       [110, 115],
       [ 30,  35],
       [ 45,  50],
       [ 55,   0],
       [  5,  15],
       [ 20,  25]])