# **Numpy_Basics_1**
**Practices**

In [1]:
pip install numpy

In [3]:
import numpy as np
dizi = np.array([0,1,2,3])
dizi

array([0, 1, 2, 3])

In [4]:
yas_dizi = np.array([18,25,22,34,36,27,19,28,30,24])
boy_dizi = np.array([1.81,1.67,1.71,1.89,1.79,1.75,1.80,1.78,1.89,1.82])
agirlik_dizi = np.array([81,72,74,88,82,77,78,70,90,85])

In [5]:
print(yas_dizi.shape)
print(boy_dizi.shape)
print(agirlik_dizi.shape)

(10,)
(10,)
(10,)


In [6]:
Listem = ["Ali", 13, True]
Dizi = np.array(Listem)
print(Dizi)

['Ali' '13' 'True']


In [8]:
Listem = [13,True]
Dizi = np.array(Listem)
print(Dizi)

[13  1]


In [9]:
dizi = np.array([0,1,2,3])
dizi[2:] = [5,4]
print(dizi)

[0 1 5 4]


In [10]:
dizi = np.array([0,1,2,3])
np.append(dizi,(7,8,9))

array([0, 1, 2, 3, 7, 8, 9])

In [13]:
w = np.array([[0,1,2,3],[4,5,6,7]])
w

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [16]:
basketball_team = np.array([[18,25,22,34,26,27,19,28,30,24], 
                           [1.81,1.67,1.71,1.89,1.79,1.75,1.80,1.78,1.89,1.82],[81,72,74,88,82,77,78,70,90,85]])
print(basketball_team)
print(basketball_team.shape)

[[18.   25.   22.   34.   26.   27.   19.   28.   30.   24.  ]
 [ 1.81  1.67  1.71  1.89  1.79  1.75  1.8   1.78  1.89  1.82]
 [81.   72.   74.   88.   82.   77.   78.   70.   90.   85.  ]]
(3, 10)


In [19]:
t = np.arange(8).reshape(2,4)
t

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [20]:
basketball_team[0,3]

34.0

In [22]:
basketball_team[0][3]

34.0

In [24]:
print(basketball_team[0])
print(basketball_team[0,])

[18. 25. 22. 34. 26. 27. 19. 28. 30. 24.]
[18. 25. 22. 34. 26. 27. 19. 28. 30. 24.]


In [25]:
basketball_team[0:2,3:7]

array([[34.  , 26.  , 27.  , 19.  ],
       [ 1.89,  1.79,  1.75,  1.8 ]])

In [26]:
dizi1 = np.array([0,1,2,3])
dizi2 = np.array([2,4,6,8])
print(dizi1*dizi2)

[ 0  4 12 24]


In [27]:
print(dizi1+dizi2)

[ 2  5  8 11]


In [28]:
vki = agirlik_dizi/boy_dizi **2
print(vki)

[24.72452001 25.81663021 25.30693205 24.63536855 25.59220998 25.14285714
 24.07407407 22.09317005 25.19526329 25.66115203]


In [31]:
print(np.ones((3,4)))
print(np.zeros((3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [32]:
np.full((3,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [33]:
np.linspace(0,20,9)

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. ])

In [34]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
x = np.array([2,3,4,5])
x = np.square(x)

In [39]:
x = np.sqrt(x)
x


array([2., 3., 4., 5.])

In [40]:
print(np.cos(x))
print(np.sin(x))

[-0.41614684 -0.9899925  -0.65364362  0.28366219]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427]


In [42]:
print(np.max(yas_dizi))
print(np.max(agirlik_dizi))
print(np.max(boy_dizi))
print(np.min(boy_dizi))
print(np.mean(yas_dizi))
print(np.std(agirlik_dizi))


36
90
1.89
1.67
26.3
6.372597586541928


**Practice** Create a 10 X 10 array of even numbers from 1 to 200.

In [55]:
np.linspace(2,200,100).reshape(10,10)

array([[  2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.],
       [ 22.,  24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.],
       [ 42.,  44.,  46.,  48.,  50.,  52.,  54.,  56.,  58.,  60.],
       [ 62.,  64.,  66.,  68.,  70.,  72.,  74.,  76.,  78.,  80.],
       [ 82.,  84.,  86.,  88.,  90.,  92.,  94.,  96.,  98., 100.],
       [102., 104., 106., 108., 110., 112., 114., 116., 118., 120.],
       [122., 124., 126., 128., 130., 132., 134., 136., 138., 140.],
       [142., 144., 146., 148., 150., 152., 154., 156., 158., 160.],
       [162., 164., 166., 168., 170., 172., 174., 176., 178., 180.],
       [182., 184., 186., 188., 190., 192., 194., 196., 198., 200.]])

**Practice** Write a function that returns an array of 1's on the sides and 0's on the inside, depending on the number of rows and columns entered as a parameter.

In [109]:
x_axis = int(input("please enter a x axis: "))
y_axis = int(input("please enter a y axis: "))
def func(x,y):
  new_array = np.zeros((x,y))
  new_array[0] = 1
  new_array[x-1] = 1
  new_array[:,0] = 1
  new_array[:,y-1] = 1
  return(new_array)
print(func(x_axis,y_axis))

please enter a x axis: 10
please enter a y axis: 5
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
